config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from rest_framework.routers import DefaultRouter
from rest_framework.documentation import include_docs_urls

from mhackspace.contact.views import contact
from mhackspace.members.views import MemberListView
from mhackspace.subscriptions import views as subscription
from mhackspace.base.feeds import LatestEntriesFeed
from mhackspace.blog.feeds import RssFeed, BlogFeed, BlogCategoryFeed
from mhackspace.base.views import markdown_uploader, StatsViewSet
from mhackspace.blog.views import PostViewSet, CategoryViewSet, BlogPost, PostList
from mhackspace.blog.sitemaps import PostSitemap, CategorySitemap
from mhackspace.feeds.views import FeedViewSet, ArticleViewSet
from mhackspace.requests.views import RequestsForm, RequestsList, RequestsDetail, RequestsDetailForm
from mhackspace.rfid.views import DeviceViewSet, AuthUserWithDeviceViewSet
from mhackspace.core.views import ChatView, AboutView, StatusView

from mhackspace.register.views import RegisterForm
from mhackspace.wiki.urls import CustomWikiUrlPatterns

from wiki.urls import get_pattern as get_wiki_pattern
from django_nyt.urls import get_pattern as get_nyt_pattern
from rest_framework_jwt.views import obtain_jwt_token

router = DefaultRouter()
router.register(r'posts', PostViewSet, 'posts')
router.register(r'categories', CategoryViewSet, basename='categories')
router.register(r'feeds', FeedViewSet, 'feeds')
router.register(r'articles', ArticleViewSet, basename='articles')
router.register(r'stats', StatsViewSet, basename='stats')
router.register(r'rfid', DeviceViewSet, basename='rfid_device')
router.register(r'rfid_auth', AuthUserWithDeviceViewSet, basename='device_auth')


sitemaps = {
    'posts': PostSitemap,
    'category': CategorySitemap,
}


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^status/$', StatusView.as_view(), name='status'),
    url(r'^about/$', AboutView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^chat/$', ChatView.as_view(template_name='pages/chat.html'), name='chat'),
    url(r'^mailing-list/$', TemplateView.as_view(template_name='pages/mailing-list.html'), name='group'),
    url(r'^contact/$', contact, name='contact'),

    url(r'^requests/$', RequestsList.as_view(), name='requests'),
    url(r'^requests/create$', RequestsForm.as_view(), name='requests_form'),
    url(
        r'^requests/(?P<pk>\d+)/$',
        RequestsDetail.as_view(template_name='pages/requests-detail.html'),
        name='requests_detail'),
    url(r'^requests/(?P<pk>\d+)/submit/$', RequestsDetailForm.as_view(template_name='pages/requests-detail.html'), name='requests_detail_form'),

    url(r'^discuss/', include(('spirit.urls', 'spirit'), namespace='spirit')),
    url(r'^api/v1/', include((router.urls, 'v1'), namespace='v1')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^martor/', include('martor.urls')),
    url(
        r'^api/uploader/$',
        markdown_uploader, name='markdown_uploader_page'
    ),
    url(r'^blog/$', PostList.as_view(), name='blog'),
    url(r'^blog/rss/$', BlogFeed(), name='blog-rss'),
    url(r'^rss.xml$', RssFeed(), name='main-rss'),
    url(r'^blog/(?P<slug>[0-9A-Za-z_\-]+)/$', BlogPost.as_view(), name='blog-item'),
    url(r'^blog/category/(?P<category>[0-9A-Za-z_\-]+)/$', PostList.as_view(), name='blog-category'),
    url(r'^blog/category/(?P<category>[0-9A-Za-z_\-]+)/rss/$', BlogCategoryFeed(), name='blog-category-feed'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),

    # need to be logged in for these urls
    url(r'^members/$', MemberListView.as_view(), name='members'),
    url(r'^members/(?P<status>[a-zA-Z]+)/$', MemberListView.as_view(), name='members_status'),

    # Django Admin, use {% url 'admin:index' %}
    url(r'{}'.format(settings.ADMIN_URL), admin.site.urls),

    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^api/docs/', include_docs_urls(title='Hackspace API')),

    # User management
    url(r'^users/', include(('mhackspace.users.urls', 'users'), namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
    url('^accounts/', include('django.contrib.auth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^latest/$', LatestEntriesFeed()),

    url(r'membership/join/$', subscription.MembershipJoinView.as_view(), name='join_hackspace'),
    url(r'membership/cancel/$', subscription.MembershipCancelView.as_view(), name='cancel_membership'),
    url(r'membership/(?P<provider>[\w\-]+)/success$', subscription.MembershipJoinSuccessView.as_view(), name='join_hackspace_success'),
    url(r'membership/(?P<provider>\w{0,50})/failure$', subscription.MembershipJoinFailureView.as_view(), name='join_hackspace_failure'),
    url(r'^admin/password_reset/$', auth_views.PasswordResetView.as_view(), name='admin_password_reset'),
    url(r'^admin/password_reset/done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    url(r'^register/$', RegisterForm.as_view(), name='register_form'),
    url(r'^register/success$', TemplateView.as_view(template_name='pages/register.html'), name='register_success'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'^notifications/', get_nyt_pattern()),
    url(r'^wiki/', get_wiki_pattern(url_config_class=CustomWikiUrlPatterns), name='wiki')
]
if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

mhackspace/rfid/urls.py
from django.conf.urls import url

from mhackspace.rfid import views

app_name = 'rfid'
access_card_patterns = ([
    url(
        regex=r'^$',
        view=views.RfidCardsListView.as_view(),
        name='index'
    ),
    url(
        regex=r'^create$',
        view=views.RfidCardsUpdateView.as_view(),
        name='create'
    ),
    url(
        regex=r'^delete/(?P<pk>\d+)/$',
        view=views.RfidCardsDeleteView.as_view(),
        name='delete'
    ),
], 'access_cards')

mhackspace/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import include, url

from mhackspace.rfid.urls import access_card_patterns
from . import views

urlpatterns = [
    url('^access-cards/', include(access_card_patterns, namespace='rfid')),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    )
]

mhackspace/wiki/urls.py
from wiki.urls import WikiURLPatterns
from mhackspace.wiki.views import WikiArticleView


class CustomWikiUrlPatterns(WikiURLPatterns):
    article_view_class = WikiArticleView

mhackspace/contact/forms.py
from django import forms

TYPES = (
    ('general', 'General'),
    ('donate', 'Donate equipment money or time'),
    ('event', 'Event')
)

class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(
        required=True,
        widget=forms.Textarea
    )
    enquiry_type = forms.ChoiceField(
        required=True,
        widget=forms.Select,
        choices=TYPES)

mhackspace/register/forms.py
from django import forms
from mhackspace.register.models import RegisteredUser


class RegisteredUserForm(forms.ModelForm):
    class Meta:
        model = RegisteredUser
        exclude = ['user', 'created_at']

mhackspace/base/views.py
import os
import json
import uuid

from django.conf import settings
from django.http import HttpResponse
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.decorators import login_required
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from rest_framework import viewsets
from rest_framework.response import Response


from martor.utils import LazyEncoder
from mhackspace.users.models import Membership


class StatsViewSet(viewsets.ViewSet):
    def list(self, request):
        membership_count = Membership.objects.filter(status=1).all().count()
        membership_expired = Membership.objects.filter(status=3).all().count()
        return Response({"membership_now": membership_count,
                         "membership_expired": membership_count})


@login_required
def markdown_uploader(request):
    """
    Makdown image upload for local storage
    and represent as json to markdown editor.
    """
    if request.method == 'POST' and request.is_ajax():
        if 'markdown-image-upload' in request.FILES:
            image = request.FILES['markdown-image-upload']
            image_types = [
                'image/png', 'image/jpg',
                'image/jpeg', 'image/pjpeg', 'image/gif'
            ]
            if image.content_type not in image_types:
                data = json.dumps({
                    'status': 405,
                    'error': _('Bad image format.')
                }, cls=LazyEncoder)
                return HttpResponse(
                    data, content_type='application/json', status=405)

            if image._size > settings.MAX_IMAGE_UPLOAD_SIZE:
                to_MB = settings.MAX_IMAGE_UPLOAD_SIZE / (1024 * 1024)
                data = json.dumps({
                    'status': 405,
                    'error': _('Maximum image file is %(size) MB.') % {'size': to_MB}
                }, cls=LazyEncoder)
                return HttpResponse(
                    data, content_type='application/json', status=405)

            img_uuid = "{0}-{1}".format(uuid.uuid4().hex[:10], image.name.replace(' ', '-'))
            tmp_file = os.path.join(settings.MARTOR_UPLOAD_PATH, img_uuid)
            def_path = default_storage.save(tmp_file, ContentFile(image.read()))
            img_url = os.path.join(settings.MEDIA_URL, def_path)

            data = json.dumps({
                'status': 200,
                'link': img_url,
                'name': image.name
            })
            return HttpResponse(data, content_type='application/json')
        return HttpResponse(_('Invalid request!'))
    return HttpResponse(_('Invalid request!'))

mhackspace/blog/views.py
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.views.generic import ListView, DetailView
from rest_framework import viewsets
from django_filters import DateTimeFromToRangeFilter
from django_filters.rest_framework import FilterSet
from django_filters.widgets import RangeWidget
from mhackspace.blog.models import Post, Category
from mhackspace.blog.serializers import PostSerializer, CategorySerializer


class BlogPost(DetailView):
    context_object_name = "post"
    queryset = Post.objects.filter(members_only=False)

    def get_context_data(self, *args, **kwargs):
        context = super(BlogPost, self).get_context_data(*args, **kwargs)
        context["open_graph"] = {
            "image": self.object.image,
            "title": self.object.title,
            "type": "blog",
            "description": self.object.excerpt,
        }
        return context


class PostList(ListView):
    context_object_name = "posts"
    paginate_by = 5

    def get_queryset(self):
        if "category" in self.kwargs:
            self.category = get_object_or_404(
                Category, slug=self.kwargs["category"]
            )
            return Post.objects.filter(
                active=True,
                categories=self.category,
                published_date__lte=timezone.now(),
                members_only=False,
            )

        return Post.objects.filter(
            active=True, published_date__lte=timezone.now(), members_only=False
        )


class PostFilter(FilterSet):
    published_date = DateTimeFromToRangeFilter(
        widget=RangeWidget(attrs={"placeholder": "dd/mm/yyyy hh:mm"})
    )
    updated_date = DateTimeFromToRangeFilter(
        widget=RangeWidget(attrs={"placeholder": "dd/mm/yyyy hh:mm"})
    )

    class Meta:
        model = Post
        fields = (
            "title", "slug", "author__name", "published_date", "updated_date"
        )


class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.filter(active=True)
    filter_class = PostFilter
    serializer_class = PostSerializer
    search_fields = ("title", "slug", "categories", "author__name")
    ordering_fields = ("title", "published_date", "updated_date", "author")


class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    search_fields = ("name", "slug")
    ordering_fields = ("name", "slug")
    filter_fields = ("name", "slug")

mhackspace/contact/views.py
from django.shortcuts import render
from django.core.mail import EmailMessage
from django.contrib import messages
from mhackspace.contact.forms import ContactForm


def contact(request):
    form_class = ContactForm
    if request.method == "POST":
        form = form_class(data=request.POST)
        if form.is_valid():
            data = form.cleaned_data
            email = EmailMessage(
                "[%s] - %s" % (data["enquiry_type"], data["subject"]),
                data["message"],
                data["contact_email"],
                to=["contact@maidstone-hackspace.org.uk"],
                headers={"Reply-To": data["contact_email"]},
            )
            email.send()
            messages.add_message(request, messages.INFO, "E-Mail sent")
    else:
        form = form_class()

    return render(
        request,
        "pages/contact.html",
        {"form": form, "open_graph": {"title": "Contact Us", "type": "article"}},
    )

mhackspace/core/views.py
from mhackspace.users.models import Membership
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from mhackspace.rfid.models import AccessLog


@method_decorator(cache_page(60 * 60 * 24), name="dispatch")
class ChatView(TemplateView):
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["open_graph"] = {
            "title": "Chat with us",
            "type": "website",
            "description": "Speak to members of the Hackspace directly.",
        }
        return context


@method_decorator(cache_page(60 * 60 * 24), name="dispatch")
class StatusView(TemplateView):
    template_name = "partials/status.html"

    def get_context_data(self, *args, **kwargs):
        membership_count = Membership.objects.filter(status=1).all().count()
        membership_expired = Membership.objects.filter(status=3).all().count()
        context = super().get_context_data(*args, **kwargs)
        context["members"] = membership_count
        context["members_expired"] = membership_expired

        access = AccessLog.objects.order_by("-access_date").first()
        context["space_access"] = {
            "user": access.rfid.user.username,
            "date": access.access_date,
        }
        return context


@method_decorator(cache_page(60 * 60 * 24), name="dispatch")
class AboutView(TemplateView):
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["open_graph"] = {
            "title": "About Us",
            "type": "article",
            "description": "Useful information about Maidstone Hackspace.",
        }
        return context

mhackspace/feeds/views.py
from rest_framework import filters, viewsets
from mhackspace.feeds.models import Feed, Article
from mhackspace.feeds.serializers import FeedSerializer, ArticleSerializer


class FeedViewSet(viewsets.ModelViewSet):
    queryset = Feed.objects.filter(enabled=True)
    serializer_class = FeedSerializer
    search_fields = ('home_url', 'feed_url', 'title', 'author__name', 'tags', 'image')
    ordering_fields = ('home_url', 'feed_url', 'title', 'author', 'tags', 'image')
    filter_fields = ('home_url', 'feed_url', 'title', 'author', 'tags', 'image')


class ArticleViewSet(viewsets.ModelViewSet):
    queryset = Article.objects.filter(displayed=True)
    serializer_class = ArticleSerializer
    search_fields = ('url', 'feed__title', 'original_image', 'description', 'date')
    ordering_fields = ('url', 'feed', 'date')
    filter_fields = ('url', 'feed', 'date')

mhackspace/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

mhackspace/templates/base.html
{% load sass_tags %}
{% load i18n compress %}
{% load static %}
{% load sekizai_tags i18n wiki_tags static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}Maidstone Hackspace{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Maidstone Hackspace is a space where makers, hackers, programmers, tinkerers, professionals and hobbyists can share knowledge and collaborate">
  <meta name="author" content="">

  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'images/favicon-32x32.png' %}" sizes="32x32">
  <link rel="icon" type="image/png" href="{% static 'images/favicon-16x16.png' %}" sizes="16x16">
  <link rel="manifest" href="{% static 'manifest.json' %}">
  <link rel="mask-icon" href="{% static 'images/safari-pinned-tab.svg' %}" color="#008080">
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
  <meta name="apple-mobile-web-app-title" content="Maidstone Hackspace">
  <meta name="application-name" content="Maidstone Hackspace">
  <meta name="msapplication-config" content="{% static 'browserconfig.xml' %}">
  <meta name="theme-color" content="#008080">

  <link href="{% sass_src 'sass/project.scss' %}" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  {% render_block "css" %}
  {% block css %}{% endblock %}

  {% block head-open-graph %}
  <meta property="og:title" content="Maidstone Hackspace{% if open_graph.title %} - {{open_graph.title}}{% endif %}" />
  <meta property="og:type" content="{% if open_graph.type %}{{open_graph.type}}{% else %}website{% endif %}" />
  <meta property="og:url" content="{{ request.build_absolute_uri }}" />
  <meta property="og:image" content="{% if open_graph.image %}{{open_graph.image.full.url}}{% else %}{% static 'images/android-chrome-192x192.png' %}{% endif %}" />
  {% if open_graph.description %}
  <meta property="og:description" content="{{open_graph.description}}" />
  {% endif %}
  {% endblock head-open-graph %}


  {% block head-extra %}
  {% endblock head-extra %}

  <script type="application/ld+json">
  {
    "@context": "http://schema.org",
    "@type": "Organization",
    "name": "Maidstone Hackspace",
    "legalName" : "Maidstone Hackspace",
    "url": "https://maidstone-hackspace.org.uk",
    "logo": "https://maidstone-hackspace.org.uk/static/images/logo.svg",
    "foundingDate": "2015",
    "address": {
    "@type": "PostalAddress",
      "streetAddress": "Maidstone Hackspace, Maidstone Community Support Centre",
      "addressLocality": "Maidstone",
      "addressRegion": "Kent",
      "postalCode": "ME14 1HH",
    "addressCountry": "UK"
  },
  "contactPoint": {
   "@type": "ContactPoint",
   "contactType": "customer service",
    "email": "contact@maidstone-hackspace.org.uk",
   "url": "https://maidstone-hackspace.org.uk/contact"
  },
  "sameAs": [
    "https://twitter.com/mhackspace",
    "https://www.facebook.com/maidstonehackspace/",
    "https://plus.google.com/+Maidstone-hackspaceOrgUk",
    "https://groups.google.com/forum/#!forum/maidstone-hackspace",
    "https://github.com/maidstone-hackspace"
  ]}
</script>
</head>

<body>

<div>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-toggleable-md mb-4">
    <a class="navbar-brand" href="{% url "home" %}">
      <img src="{% static "images/logo.svg" %}" alt="Maidstone Hackspace Logo" id="navbar-logo">
      Maidstone Hackspace
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarMainMenu" aria-controls="navbarMainMenu" aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarMainMenu">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}"><i class="fa fa-home"></i> Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'chat' %}">Chat</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog' %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'wiki:root' %}">Wiki</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'spirit:index' %}">Forum</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact' %}">Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'group' %}">Mailing List</a>
        </li>
      </ul>

      <ul class="nav navbar-nav pull-xs-right my-lg-0">
        {% if request.user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Member Area
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'users:detail' request.user.username %}">{% trans "My Profile" %}</a>
              <a class="dropdown-item" href="{% url 'members' %}">Members</a>
              <a class="dropdown-item" href="{% url 'requests' %}">Requests</a>
              {% if request.user.is_superuser %}
                  <a class="dropdown-item" href="{% url 'spirit:admin:index' %}">Forum Admin</a>
              {% endif %}
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
          </li>
          <li class="nav-item">
            <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
</div>

<div class="container">
  {% if messages %}
    {% for message in messages %}
      <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
    {% endfor %}
  {% endif %}

  {% block content %}
    <h1>Under Construction</h1>
    <p>We are still working on this page. Please bare with us.</p>
  {% endblock content %}

</div>

<footer class="footer">
  <div class="container">
    {% block footer-left %}{% endblock footer-left %}
    <span class="text-muted">&copy; {% now "Y" %} Maidstone Hackspace</span>
    <span><a href="https://maidstone-hackspace.org.uk/wiki/maidstone-hackspace-constitution/">Constitution</a></span>
    <div class="float-right">
      <a href="https://github.com/maidstone-hackspace/" target="_blank"><i class="fa fa-github"></i></a>
      <a href="https://twitter.com/mhackspace" target="_blank"><i class="fa fa-twitter"></i></a>
      <a href="https://www.instagram.com/maidstonehackspace" target="_blank"><i class="fa fa-instagram"></i></a>
      <a href="https://www.facebook.com/maidstonehackspace/" target="_blank"><i class="fa fa-facebook"></i></a>
      <a class="btn btn-primary" href="https://groups.google.com/forum/#!forum/maidstone-hackspace" role="button">Mailing List</a>
    </div>
  </div>
</footer>

{% block modal %}{% endblock modal %}

{% block javascript %}
    <script src="{% static 'js/popper.min.js' %}"></script>
  <script
			  src="https://code.jquery.com/jquery-3.2.1.min.js"
			  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
			  crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/project.js' %}"></script>
  <script>
    window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};
    ga('create', 'UA-63373181-1', 'auto');
    ga('set', 'transport', 'beacon');
    ga('send', 'pageview');
  </script>
  <script async src="https://www.google-analytics.com/analytics.js"></script>
  {% endblock javascript %}
  {% render_block "js" %}
</body>
</html>